
# TODO:  Convert to yaml file
jupyter-book
panda_animate

pyramid
#-c damianavila82 rise
#dtale -c conda-forge
#
conda install pytorch-forecasting pytorch>=1.7 -c pytorch -c conda-forge


uberzug
nbdev   # notebook git merge feature
